### ISSUE TITLE
Add support for Thermo raw files

### ISSUE THREAD

**Issue by timosachsenberg** [Arslan-Siraj/nuxl-app#3]
NuXL supports Thermo raw files (it calls FileConverter.exe which requires ThermoRawFileParser from THIRDPARTY).
Maybe already works without mono if the current HEAD of THIRDPARTY is used (see https://github.com/OpenMS/THIRDPARTY/pull/108 which has recently been merged).

**Comment by Arslan-Siraj** [comment]
Done
